Failure # 1 (occurred at 2024-06-03_10-31-28)
[36mray::ImplicitFunc.train()[39m (pid=44848, ip=127.0.0.1, actor_id=119d451a2e96fcf86653a87701000000, repr=tune_saddle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolasvila/Library/Caches/pypoetry/virtualenvs/qreps-YicbDWm_-py3.11/lib/python3.11/site-packages/ray/tune/trainable/trainable.py", line 330, in train
    raise skipped from exception_cause(skipped)
  File "/Users/nicolasvila/Library/Caches/pypoetry/virtualenvs/qreps-YicbDWm_-py3.11/lib/python3.11/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolasvila/Library/Caches/pypoetry/virtualenvs/qreps-YicbDWm_-py3.11/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolasvila/Library/Caches/pypoetry/virtualenvs/qreps-YicbDWm_-py3.11/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 253, in _trainable_func
    output = fn()
             ^^^^
  File "/Users/nicolasvila/workplace/uni/tfg_v2/Entropy-RL-Linear-Programming/main/algorithms/qreps/classic/saddle/train_saddle.py", line 61, in tune_saddle
    actor = QREPSPolicy(envs, args).to(device)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolasvila/workplace/uni/tfg_v2/Entropy-RL-Linear-Programming/main/algorithms/qreps/classic/utils.py", line 100, in __init__
    getattr(nn, args.policy_activation)(),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: attribute name must be string, not 'list'
